### ISSUE TITLE
Bug: Nothing displayed to user if JSON cannot be read

### ISSUE THREAD

**Issue by jia-han** [AY2223S1-CS2103T-T15-3/tp#146]
Currently, an error message is logged if the Tuthub JSON is in an incorrect format, e.g: `WARNING: Data file not in the correct format. Will be starting with an empty Tuthub`. However, the error message is not displayed to the user.

We can improve user-friendliness by displaying the error message to the user.

**Comment by t1mzzz** [comment]
`MainApp` starts up Ui last, hence it might not make sense to start up a ResultDisplay before the UI has started. As a result, a better option might be to inform the users in the User Guide regarding this possible issue (possibly in the FAQ section).

**Comment by jia-han** [comment]
Agreed, we could direct the user to the log files to determine the exact cause through the FAQ.
