### ISSUE TITLE
[PE-D][Tester A] Ratings

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-3/tp#221]
It is not mentioned anywhere in the UG or error message what the rating is out of. Based on testing, it seems like it is out of 5.0, but as it was not mentioned before, I though I could enter 10.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: HoJunHao2000/ped#2

**Comment by jia-han** [comment]
Same as #243
