### ISSUE TITLE
[PE-D][Tester C] UG bug in "add" command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-3/tp#222]
Examples given in "add" command is not further explained so it will be difficult for the user to know what is being added

![image.png](https://raw.githubusercontent.com/jjtan444/ped/main/files/399a698c-bc76-487f-9322-abfcfcea85c7.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jjtan444/ped#5

**Comment by fannyjian** [comment]
Closed via #249
