### ISSUE TITLE
[PE-D][Tester E] BUG: Formatting error in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-3/tp#232]
The seventh example has a formatting error.
![image.png](https://raw.githubusercontent.com/vantemoon/ped/main/files/592dbb65-c56e-4e0d-94fd-30605b453ff8.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: vantemoon/ped#7

**Comment by fannyjian** [comment]
Closed by PR #249
