### ISSUE TITLE
As a user, I can view the tutor's details in a larger window

### ISSUE THREAD

**Issue by t1mzzz** [AY2223S1-CS2103T-T15-3/tp#98]
... so that I have a complete view and understanding of the tutor profile.

Tasks:
- [x]  Add view command
- [x]  Add test cases
- [x]  Update UG and DG
- [x]  Enable view on click function

**Comment by fannyjian** [comment]
Tasks: 
- [ ] Add view command
- [ ] Add test cases
- [ ] Update UG and DG
- [ ] Enable view on click function
